import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ThemeProvider } from "@/components/providers/theme-provider"
import { ToastContainer } from "@/components/ui/toaster"
import TanstackProvider from "@/components/providers/tanstack-provider"
import NextTopLoader from "nextjs-toploader"
import Navbar from "@/components/main/navbar"
import "@/app/globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Home | Next Template",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-gray-50 dark:bg-background`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader showSpinner={false} />
          <TanstackProvider>
            <Navbar />
            <main className="container">{children}</main>
          </TanstackProvider>
          <ToastContainer />
        </ThemeProvider>
      </body>
    </html>
  )
}
